version: '3.8'
services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongo_cluster

  mongo2:
    image: mongo:6.0
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongo_cluster

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--bind_ip", "0.0.0.0"]
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongo_cluster

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  mongo_cluster: